services:
  mee2027:
    image: mee2027:latest
    container_name: mee2027
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8040:4321"
    networks:
      - webnet


networks:
  webnet:
    driver: bridge
