export type MenuTab = 'Astrometría' | 'Distorsión' | 'Deflexión' | 'Apéndices' | 'Presentación' | 'Biblio';

export interface DocItem {
  filename: string;
  menutab: MenuTab;
  id: string;
  slug: string;
  description: string;
  chapter: string;
}

export const docList: DocItem[] = [
  {
    filename: 'my_centroids_stack_playsolve.md',
    menutab: 'Astrometría',
    id: 'my_centroids_stack_playsolve',
    slug: 'my_centroids_stack_playsolve',
    description: 'Centroides, Apilado y PlateSolving',
    chapter: '1',
  },
  {
    filename: 'parametros.md',
    menutab: 'Astrometría',
    id: 'parametros',
    slug: 'parametros',
    description: 'Parámetros',
    chapter: '1.1',
  },
  {
    filename: '00_crear_bases_datos.md',
    menutab: 'Astrometría',
    id: '00_crear_bases_datos',
    slug: '00_crear_bases_datos',
    description: 'Estructuras KDtree desde Tycho',
    chapter: '1.2',
  },
  {
    filename: 'my_database.md',
    menutab: 'Astrometría',
    id: 'my_database',
    slug: 'my_database',
    description: 'Base de datos',
    chapter: '2',
  },
    {
    filename: 'my_platesolve_new.md',
    menutab: 'Astrometría',
    id: 'my_platesolve_new',
    slug: 'my_platesolve_new',
    description: 'Construcción (generador) V1',
    chapter: '2.1',
  },
  {
    filename: 'my_platesolve_new_commented2.md',
    menutab: 'Astrometría',
    id: 'my_platesolve_new_commented2',
    slug: 'my_platesolve_new_commented2',
    description: 'Construcción (generador) V2',
    chapter: '2.2',
  }, 
  {
    filename: 'my_database_lookup2.md',
    menutab: 'Astrometría',
    id: 'my_database_lookup2',
    slug: 'my_database_lookup2',
    description: 'Indexación',
    chapter: '2.3',
  },
  {
    filename: 'my_database_cache.md',
    menutab: 'Astrometría',
    id: 'my_database_cache',
    slug: 'my_database_cache',
    description: 'Persistencia',
    chapter: '2.4',
  },
 {
    filename: 'my_database_searcher.md',
    menutab: 'Astrometría',
    id: 'my_database_searcher',
    slug: 'my_database_searcher',
    description: 'Búsqueda',
    chapter: '2.5',
  },

  {
    filename: 'my_stacker_implementattion.md',
    menutab: 'Astrometría',
    id: 'my_stacker_implementattion',
    slug: 'my_stacker_implementattion',
    description: 'Centroides y Apilado',
    chapter: '3',
  },
  {
    filename: 'my_stacker_implementattion - attempt_align - datos.md',
    menutab: 'Astrometría',
    id: 'my_stacker_implementattion---attempt_align-datos---datos', 
    slug: 'my_stacker_implementattion---attempt_align---datos',
    description: '. Datos de apilado',
    chapter: '3.1',
  },
  {
    filename: '07_attempt_align.md',
    menutab: 'Astrometría',
    id: '07_attempt_align',
    slug: '07_attempt_align',
    description: 'Apilado',
    chapter: '3.2',
  },
  {
    filename: 'my_platesolve_triangle.md',
    menutab: 'Astrometría',
    id: 'my_platesolve_triangle',
    slug: 'my_platesolve_triangle',
    description: 'PlateSolve. Resolución de placas',
    chapter: '4',
  },
  {
    filename: 'my_distortion_fitter.md',
    menutab: 'Distorsión',
    id: 'my_distortion_fitter',
    slug: 'my_distortion_fitter',
    description: 'Ajuste de la distorsión',
    chapter: '1',
  },
  {
    filename: 'my_distortion_diagram1.md',
    menutab: 'Distorsión',
    id: 'my_distortion_diagram1',
    slug: 'my_distortion_diagram1',
    description: 'Diagrama de distorsión 1',
    chapter: '1.1',
  },
  {
    filename: 'my_distortion_diagram2.md',
    menutab: 'Distorsión',
    id: 'my_distortion_diagram2',
    slug: 'my_distortion_diagram2',
    description: 'Diagrama de distorsión 2',
    chapter: '1.2',
  },

  {
    filename: 'my_distortion_fitter - match_and_fit_distortion.md',
    menutab: 'Distorsión',
    id: 'my_distortion_fitter---match_and_fit_distortion',
    slug: 'my_distortion_fitter-match-and-fit-distortion',
    description: '. Ajuste y coincidencia',
    chapter: '1.3',
  },
  {
    filename: 'my_distortion_fitter - match_centroids.md',
    menutab: 'Distorsión',
    id: 'my_distortion_fitter---match_centroids',
    slug: 'my_distortion_fitter-match-centroids',
    description: '. Coincidencia de centroides',
    chapter: '1.4',
  },
  {
    filename: 'my_distortion_polynomial.md',
    menutab: 'Distorsión',
    id: 'my_distortion_polynomial',
    slug: 'my_distortion_polynomial',
    description: 'Distorsión polinomial',
    chapter: '2',
  },
  {
    filename: 'my_distortion_polynomial - do_cubic_fit.md',
    menutab: 'Distorsión',
    id: 'my_distortion_polynomial---do_cubic_fit',
    slug: 'my_distortion_polynomial-do-cubic-fit',
    description: '. Ajuste cúbico',
    chapter: '2.1',
  },
  {
    filename: 'my_distortion_polynomial - _cubic_helper.md',
    menutab: 'Distorsión',
    id: 'my_distortion_polynomial---_cubic_helper',
    slug: 'my_distortion_polynomial-cubic-helper',
    description: '. Asistente cúbico',
    chapter: '2.2',
  },
  {
    filename: 'my_distortion_polynomial - apply_corrections.md',
    menutab: 'Distorsión',
    id: 'my_distortion_polynomial---apply_corrections',
    slug: 'my_distortion_polynomial-apply-corrections',
    description: '. Aplicar correcciones',
    chapter: '2.3',
  },
  {
    filename: 'my_platesolve_triangle - platesolve.md',
    menutab: 'Distorsión',
    id: 'my_platesolve_triangle---platesolve',
    slug: 'my_platesolve_triangle-platesolve',
    description: 'Triangulación para platesolve',
    chapter: '3',
  },
  {
    filename: 'my_platesolve_triangle - _platesolve _helper.md',
    menutab: 'Distorsión',
    id: 'my_platesolve_triangle---_platesolve-_helper',
    slug: 'my_platesolve_triangle-platesolve-helper',
    description: '. Asistente platesolve',
    chapter: '3.1',
  },
  {
    filename: 'my_refraction_correction.md',
    menutab: 'Distorsión',
    id: 'my_refraction_correction',
    slug: 'my_refraction_correction',
    description: 'Corrección de refracción',
    chapter: '4',
  },
  {
    filename: 'my_gravity_sweep.md',
    menutab: 'Distorsión',
    id: 'my_gravity_sweep',
    slug: 'my_gravity_sweep',
    description: 'Barrido gravitacional',
    chapter: '5',
  },
  {
    filename: 'my_gaia_search.md',
    menutab: 'Distorsión',
    id: 'my_gaia_search',
    slug: 'my_gaia_search',
    description: 'Búsqueda en Gaia',
    chapter: '6',
  },
  {
    filename: '02_eclipse_analysis.md',
    menutab: 'Deflexión',
    id: '02_eclipse_analysis',
    slug: '02_eclipse_analysis',
    description: 'Análisi del Eclipse',
    chapter: '1',
  },
  {
    filename: 'Métodos de optimización.md',
    menutab: 'Apéndices',
    id: 'métodos-de-optimización',
    slug: 'métodos-de-optimización',
    description: 'Algoritmos de optimización',
    chapter: '1',
  },
    {
    filename: 'Basados en el gradiente.md',
    menutab: 'Apéndices',
    id: 'basados-en-el-gradiente',
    slug: 'basados-en-el-gradiente',
    description: '. Basados en el Gradiente',
    chapter: '1.1',
  },
     {
    filename: 'Metodo de Newton.md',
    menutab: 'Apéndices',
    id: 'metodo-de-newton',
    slug: 'metodo-de-newton',
    description: '. Método de Newton',
    chapter: '1.2',
  },
  {
    filename: 'Algoritmo_BFGS.md',
    menutab: 'Apéndices',
    id: 'algoritmo_bfgs',
    slug: 'algoritmo_bfgs',
    description: '. Algoritmo BFGS',
    chapter: '1.3',
  },
    {
    filename: 'scipy-optimize-minimize.md',
    menutab: 'Apéndices',
    id: 'scipy-optimize-minimize',
    slug: 'scipy-optimize-minimize',
    description: '. scipy.optimize.minimize',
    chapter: '1.4',
  },
  {
    filename: '1. Función de Rosenbrock.md',
    menutab: 'Apéndices',
    id: '1-función-de-rosenbrock',
    slug: '1-función-de-rosenbrock',
    description: 'La función de Rosenbrock',
    chapter: '2',
  },    
  {
    filename: '2. Función multidimensional de Rosenbrock.md',
    menutab: 'Apéndices',
    id: '2-función-multidimensional-de-rosenbrock',
    slug: '2-función-multidimensional-de-rosenbrock',
    description: 'La función multidimensional de Rosenbrock',
    chapter: '2.1',
  },   
  {
    filename: 'La matriz Hessiana.md',
    menutab: 'Apéndices',
    id: 'la-matriz-hessiana',
    slug: 'la-matriz-hessiana',
    description: 'Matriz Hessiana de Rosenbrock',
    chapter: '2.2',
  },  
  {
    filename: 'Teorema de Taylor.md',
    menutab: 'Apéndices',
    id: 'teorema-de-taylor',
    slug: 'teorema-de-taylor',
    description: 'Teorema de Taylor multidimensional',
    chapter: '3',
  },  
  {
    filename: 'k-d_Tree_Architecture.md',
    menutab: 'Presentación',
    id: 'k-d_tree_architecture',
    slug: 'k-d_tree_architecture',
    description: 'Arquitectura Árboles KDtree',
    chapter: '1',
  },  
  {
    filename: 'Entrevista.md',
    menutab: 'Presentación',
    id: 'entrevista',
    slug: 'entrevista',
    description: 'Entrevista TV',
    chapter: '2',
  },  
  {
    filename: 'Entrevista1.md',
    menutab: 'Presentación',
    id: 'entrevista1',
    slug: 'entrevista1',
    description: 'Curvatura de la luz',
    chapter: '2.1',
  },  
  {
    filename: 'Entrevista2.md',
    menutab: 'Presentación',
    id: 'entrevista2',
    slug: 'entrevista2',
    description: 'Experimento de Eddington',
    chapter: '2.2',
  }, 
  {
    filename: 'Entrevista3.md',
    menutab: 'Presentación',
    id: 'entrevista3',
    slug: 'entrevista3',
    description: 'Eddington paso a paso',
    chapter: '2.3',
  },  
  {
    filename: 'Entrevista4.md',
    menutab: 'Presentación',
    id: 'entrevista4',
    slug: 'entrevista4',
    description: 'El proyecto MEE2027',
    chapter: '2.4',
  },  
  {
    filename: 'Entrevista5.md',
    menutab: 'Presentación',
    id: 'entrevista5',
    slug: 'entrevista5',
    description: 'Diferencias del experimento original',
    chapter: '2.5',
  },
  {
    filename: 'Entrevista6.md',
    menutab: 'Presentación',
    id: 'entrevista6',
    slug: 'entrevista6',
    description: 'Quién está involucrado',
    chapter: '2.6',
  },
  {
    filename: 'Entrevista7.md',
    menutab: 'Presentación',
    id: 'entrevista7',
    slug: 'entrevista7',
    description: '2026: Ensayo general',
    chapter: '2.7',
  },
  {
    filename: 'Entrevista8.md',
    menutab: 'Presentación',
    id: 'entrevista8',
    slug: 'entrevista8',
    description: 'Ensayo en 2026 y Objetivo 2027',
    chapter: '2.8',
  },
  {
    filename: 'Entrevista9.md',
    menutab: 'Presentación',
    id: 'entrevista9',
    slug: 'entrevista9',
    description: 'El trío ibérico de eclipses',
    chapter: '2.9',
  },  
  {
    filename: 'Plantilla.md',
    menutab: 'Biblio',
    id: 'plantilla',
    slug: 'plantilla',
    description: 'Plantilla para nuevos documentos',
    chapter: '1',
  },
    {
    filename: 'midu-docker.md',
    menutab: 'Biblio',
    id: 'midu-docker',
    slug: 'midu-docker',
    description: 'Docker desde cero',
    chapter: '2.1',
  },  
];

export const docMapById = new Map<string, DocItem>(
  docList.map(item => [item.id, item])
);

export const docMapBySlug = new Map<string, DocItem>(
  docList.map(item => [item.slug, item])
);
